### PR TITLE
Added an appropriate scolding text to the system

### PR DESCRIPTION
**Pull request by rishabhk1796**
Added an appropriate scolding text to the system

### CODE REVIEW

**Comment by ghost** [comment]
Got it, will review in a sec.

**Review by ghost — CHANGES_REQUESTED** [review]
Let’s try this again, shall we?

**Review by ghost — CHANGES_REQUESTED** [review]
Some issues need to be fixed before you can merge your PR:
 - I have no idea why, but I've been told that we are not allowed to update "docker-compose.yml". Please make sure to revert your changes before merging your PR.

**Comment by rishabhk1796** [comment]
Check my PR

**Pull request closed without merging**
